services:
  jupyter:
    build: .
    container_name: gps_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./src:/workspace/src
    environment:
      - CONDA_ENV=gps-analytics
    tty: true
