name: gps-analytics
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyspark
  - pip
  - pip:
      - jupyterlab
      - ipykernel
      - pandas
      - numpy
      - scikit-learn
      - matplotlib